// SPDX-FileCopyrightText: 2025 Yale University
// SPDX-License-Identifier: Apache-2.0

// Code is generated by the EAASI SDK-Generator:
// https://github.com/eaasi/sdk-generator

// DO NOT EDIT THIS FILE MANUALLY!

import createClient from "openapi-fetch";
import type { Client, ClientOptions } from "openapi-fetch";
import type { paths as ApiV1alpha } from "./api/v1alpha.ts";

/** Create new client for EAASI API v1alpha */
export function createClientV1alpha(options: ClientOptions): Client<ApiV1alpha> {
	return createClient<ApiV1alpha>(options);
}

// Re-export everything for advanced use-cases!
export * as v1alpha from "./api/v1alpha.ts";
export * from "openapi-fetch";
export default createClient;
